spring:
  datasource:
    url: jdbc:postgresql://localhost:4444/accounting_db
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
  config:
    import: optional:secret.yml

server:
  url: http://localhost:8080

