spring:
  datasource:
    url: jdbc:postgresql://localhost:4444/accounting_db
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

server:
  url: http://localhost:8080
